version: "3.3"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL= Obytes@localhost.com
      - PGADMIN_DEFAULT_PASSWORD= postgres
    ports:
      - "80:80"
  queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SECRET_COOKIE"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
      - "5672:5672"
      - "15672:15672"
  flower:
    image: mher/flower
    networks:
      - default
    environment:
      - FLOWER_BASIC_AUTH=username:password
    command:
      - "--broker=amqp://guest:guest@queue:5672/"
  backend:
    depends_on:
      - db
      - queue
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - docker-compose.env
    ports:
      - "8000:8000"
    image: fastql
