name: Docker-Compose Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: pull latest
        run: docker-compose pull
      - name: Build image
        run: docker-compose build
      - name: Test code format -- pre-commit
        run: make lint